[project]
name = "win-agent"
version = "0.1.0"
description = "Browser automation agent for Windows"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "browser-use>=0.5.6",
    "python-dotenv>=1.0.0",
    "playwright>=1.40.0",
]
